import type { Locale } from './theme';

export const messages = {
  ru: {
    brand: 'Widget Grove',
    eyebrow: 'Персональные виджеты для профиля и команд',
    title: 'Собирайте живые виджеты в одном стеклянном пространстве',
    subtitle:
      'Создавайте галереи из GitHub-статистики, языков, активности и любых будущих источников. Первый экран показывает общий стиль продукта.',
    signin: 'Вход',
    signup: 'Регистрация',
    signinTitle: 'С возвращением',
    signinSubtitle: 'Войдите, чтобы открыть галерею своих виджетов.',
    signupTitle: 'Создайте пространство виджетов',
    signupSubtitle: 'Зарегистрируйтесь и начните собирать персональную витрину.',
    authCta: 'Перейти к регистрации',
    profile: 'Максим',
    oauthYandex: 'Продолжить с Яндекс ID',
    orEmail: 'или через email',
    email: 'Email',
    password: 'Пароль',
    name: 'Имя',
    continue: 'Продолжить',
    demoAuth: 'Демо авторизация',
    widgets: 'Мои виджеты',
    home: 'Главная',
    chats: 'Чаты',
    newNote: 'Новая заметка',
    language: 'Язык',
    theme: 'Тема',
    widgetsLead: 'Галерея созданных вами виджетов. Источники могут быть любыми, не только GitHub.',
    recentWidgets: 'Последние виджеты',
    gallery: 'Галерея',
    logout: 'Выйти',
    expand: 'Меню',
    createWidget: 'Создать виджет',
    open: 'Открыть',
    configure: 'Настроить',
    active: 'Активен',
    draft: 'Черновик',
    updated: 'Обновлено',
  },
  en: {
    brand: 'Widget Grove',
    eyebrow: 'Personal widgets for profiles and teams',
    title: 'Build live widgets in one glass workspace',
    subtitle:
      'Create galleries from GitHub stats, languages, activity, and any future sources. This first screen focuses on the product look and feel.',
    signin: 'Sign in',
    signup: 'Sign up',
    signinTitle: 'Welcome back',
    signinSubtitle: 'Sign in to open your widget gallery.',
    signupTitle: 'Create your widget space',
    signupSubtitle: 'Sign up and start building a personal showcase.',
    authCta: 'Go to sign up',
    profile: 'Maksim',
    oauthYandex: 'Continue with Yandex ID',
    orEmail: 'or use email',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    continue: 'Continue',
    demoAuth: 'Demo auth',
    widgets: 'My widgets',
    home: 'Home',
    chats: 'Chats',
    newNote: 'New note',
    language: 'Language',
    theme: 'Theme',
    widgetsLead: 'A gallery of widgets you created. Sources can be anything, not only GitHub.',
    recentWidgets: 'Recent widgets',
    gallery: 'Gallery',
    logout: 'Log out',
    expand: 'Menu',
    createWidget: 'Create widget',
    open: 'Open',
    configure: 'Configure',
    active: 'Active',
    draft: 'Draft',
    updated: 'Updated',
  },
} satisfies Record<Locale, Record<string, string>>;

export const widgets = [
  { title: 'GitHub Stats', source: 'GitHub', status: 'active', metric: '2.4k', accent: 'lavender' },
  { title: 'Languages Mix', source: 'GitHub', status: 'active', metric: 'TS 68%', accent: 'mint' },
  { title: 'Release Pulse', source: 'Custom API', status: 'draft', metric: '12', accent: 'blue' },
  {
    title: 'Team Activity',
    source: 'Workspace',
    status: 'active',
    metric: '+18%',
    accent: 'violet',
  },
] as const;
